---
title: "Model fitting Summary"
output:
  html_document:
    toc: yes
    self_contained: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    number_sections: False
    highlight: pygments
    theme: cosmo
    code_folding: "hide"
    df_print: paged
    fig_caption: true
  pdf_document:
    toc: yes
    fig_caption: true
    latex_engine: xelatex
fig.align: "center"
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{AgfaRotisSansSerif}
email: koch@mpib-berlin.mpg.de
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(data.table)
library(here)
library(magrittr)
library(ggplot2)
library(viridis)
library(plotly)
library(plyr)
```

```{r}
# Get directory of repository
base_path = here::here()

# Load pre-written functions
source_path = file.path(base_path, 'code', 'utils',
                        fsep = .Platform$file.sep)
source_files = list.files(source_path, pattern = "[.][rR]$",
                          full.names = TRUE, recursive = TRUE)
invisible(lapply(source_files, function(x) source(x)))
```


```{r}
# Load data
data = Load_model_fits()

# Get number of participants
n_participants = length(unique(data$participant_id))

# Get all designs
all_designs = Load_data()
```

# Fitting consistency

```{r}
Plot_prepare_consistency = function(data){
  data_plot = data %>%
    data.table::melt(., id.vars = c('participant_id',
                                    'file',
                                    'iter',
                                    'task_version',
                                    'name_design_r1',
                                    'name_design_r2',
                                    'model',
                                    'para',
                                    'first_status',
                                    'first_ll',
                                    'second_status',
                                    'second_ll'),
                     measure.vars = c('first_x0',
                                      'second_solution'),
                     value.name = 'val') %>%
    .[, variable := factor(variable, levels = c('first_x0',
                                                'second_solution'))] %>%
    # Join iterations of across jobs and within jobs
    .[, real_iter := seq(.N),
      by = c('participant_id',
             'task_version',
             'name_design_r1',
             'name_design_r2',
             'model',
             'para',
             'variable')] %>%
    # Delete previous iteration columns
    .[, ':='(iter = NULL,
             file = NULL)] %>%
    data.table::dcast(.,
                      participant_id + 
                        real_iter +
                        task_version + 
                        name_design_r1 + 
                        name_design_r2 + 
                        model +
                        first_status + 
                        first_ll + 
                        second_status + 
                        second_ll + 
                        variable ~ paste0('value_', para), value.var = 'val')
  
  return(data_plot)
}
```

## Rw

```{r, out.width='100%', fig.height=n_participants}
data_plot = Plot_prepare_consistency(data[model == 'Rw'])

ggplot(data = data_plot,
       aes(x = value_alpha,
           y = value_temperature,
           fill = variable,
           shape = variable,
           group = real_iter)) +
  scale_fill_manual(values = c('white', 'black')) +
  scale_shape_manual(values = c(21, 24)) +
  scale_x_continuous(limits = c(0,1)) +
  scale_y_continuous(limits = c(0,10)) +
  geom_path(color = 'black',
            size = 0.2,
            alpha = 0.3) +
  geom_point(size = 0.8,
             stroke = 0.3,
             color = 'black',
             alpha = 0.5) +
  facet_grid(participant_id ~ task_version) +
  theme(legend.position = 'bottom')
```

## Pedlr

```{r, warning=FALSE, fig.show='hold'}
data_plot = Plot_prepare_consistency(data[model == 'Pedlr'])

for(pid in unique(data_plot$participant_id)){
  data_plot_i = data_plot[participant_id == pid]
  fig = plotly::plot_ly(x = data_plot_i$value_alpha0,
                        y = data_plot_i$value_alpha1,
                        z = data_plot_i$value_temperature,
                        type = "scatter3d",
                        mode = 'markers',
                        color = data_plot_i$variable,
                        size = nchar(as.character(data_plot_i$variable)) * 0.1) %>%
    plotly::layout(title = unique(data_plot_i$participant_id))
  
  print(fig)
}
```

## Pedlr_interdep

```{r, warning=FALSE, fig.show='hold'}
data_plot = Plot_prepare_consistency(data[model == 'Pedlr_interdep'])

for(pid in unique(data_plot$participant_id)){
  data_plot_i = data_plot[participant_id == pid]
  fig = plotly::plot_ly(x = data_plot_i$value_alpha0,
                        y = data_plot_i$value_alpha1,
                        z = data_plot_i$value_temperature,
                        type = "scatter3d",
                        mode = 'markers',
                        color = data_plot_i$variable,
                        size = nchar(as.character(data_plot_i$variable)) * 0.1) %>%
    plotly::layout(title = unique(data_plot_i$participant_id))
  
  print(fig)
}
```

# Model vs. participants

```{r}
# Function to append model values as columns to design file
Append_model_values = function(data, model_output){
  data$model_choice = model_output$choices$choice
  data$model_choice_prob = model_output$choices$choice_prob
  data$model_value_1 = model_output$values$stim_1
  data$model_value_2 = model_output$values$stim_2
  data$model_value_3 = model_output$values$stim_3
  data$model_pe_1 = model_output$PE$stim_1
  data$model_pe_2 = model_output$PE$stim_2
  data$model_pe_3 = model_output$PE$stim_3
  data$model_fpe_1 = model_output$fPE$stim_1
  data$model_fpe_2 = model_output$fPE$stim_2
  data$model_fpe_3 = model_output$fPE$stim_3
  
  return(data)
}

# Get data for best fitting model
data_best = Get_best_fit(data)

# Simulate data based on best fitting parameters
data_best_fitting_paras = data.table()
for(id in unique(all_designs$participant_id)){
  for(run in unique(all_designs$task_version)){
    # Rw
    sim = Rw(design = all_designs[participant_id == id & task_version == run],
             params.alpha = data_best[participant_id == id & task_version == run & model == 'Rw',
                                      second_solution_alpha],
             params.temperature = data_best[participant_id == id & task_version == run & model == 'Rw',
                                            second_solution_temperature],
             params.reward_space_ub = 100,
             choice_policy = 'softmax',
             init_values = c(50,50,50))
    temp = all_designs[participant_id == id & task_version == run]
    temp$model = 'Rw'
    temp = Append_model_values(data = temp, model_output = sim)
    data_best_fitting_paras = rbind(data_best_fitting_paras, temp)
    
    # Pedlr
    sim = Pedlr(design = all_designs[participant_id == id & task_version == run],
                params.alpha0 = data_best[participant_id == id & task_version == run & model == 'Pedlr',
                                          second_solution_alpha0],
                params.alpha1 = data_best[participant_id == id & task_version == run & model == 'Pedlr',
                                          second_solution_alpha1],
                params.temperature = data_best[participant_id == id & task_version == run & model == 'Pedlr',
                                               second_solution_temperature],
                params.reward_space_ub = 100,
                choice_policy = 'softmax',
                init_values = c(50,50,50))
    temp = all_designs[participant_id == id & task_version == run]
    temp$model = 'Pedlr'
    temp = Append_model_values(data = temp, model_output = sim)
    data_best_fitting_paras = rbind(data_best_fitting_paras, temp)
    
    # Pedlr_interdep
    sim = Pedlr_interdep(design = all_designs[participant_id == id & task_version == run],
                         params.alpha0 = data_best[participant_id == id & task_version == run & model == 'Pedlr_interdep',
                                                   second_solution_alpha0],
                         params.alpha1 = data_best[participant_id == id & task_version == run & model == 'Pedlr_interdep',
                                                   second_solution_alpha1],
                         params.interdep = data_best[participant_id == id & task_version == run & model == 'Pedlr_interdep',
                                                     second_solution_interdep],
                         params.temperature = data_best[participant_id == id & task_version == run & model == 'Pedlr_interdep',
                                                        second_solution_temperature],
                         params.reward_space_ub = 100,
                         choice_policy = 'softmax',
                         init_values = c(50,50,50))
    temp = all_designs[participant_id == id & task_version == run]
    temp$model = 'Pedlr_interdep'
    temp = Append_model_values(data = temp, model_output = sim)
    data_best_fitting_paras = rbind(data_best_fitting_paras, temp)
  }
}
```

```{r}
Plot_prepare_correspondence = function(data){
  # Get columns of estimations
  est_cols = c('est_1_reward', 'est_2_reward', 'est_3_reward',
               'model_value_1', 'model_value_2', 'model_value_3')
  
  data_plot = data %>%
    .[, trial := seq(.N),
      by = c('participant_id', 'task_version', 'model')] %>%
    .[, (est_cols) := lapply(.SD, as.numeric), .SDcols = est_cols] %>%
    data.table::melt(.,
                     id.vars = c('participant_id', 'task_version', 'model', 'trial'),
                     measure.vars = c('est_1_reward', 'est_2_reward', 'est_3_reward',
                                      'model_value_1', 'model_value_2', 'model_value_3')) %>%
    .[!is.na(value),] %>%
    .[, ':='(type = unlist(strsplit(as.character(variable), split = '_'))[1],
             stim = sort(unlist(strsplit(as.character(variable), split = '_')))[1]),
      by = c('participant_id', 'task_version', 'model', 'trial', 'variable')] %>%
    .[, ':='(type = as.factor(type),
             stim = as.factor(stim))]
  
  return(data_plot)
}

# Prepare all data for plotting correspondence
data_plot = Plot_prepare_correspondence(data_best_fitting_paras)
```

```{r, out.width='100%', fig.height=n_participants}
ggplot(data = data_plot[type == 'est'],
       aes(x = trial,
           y = value)) +
  geom_line(color = 'black',
            linetype = 'dashed') +
  geom_point(color = 'black',
             size = 0.3,
             alpha = 0.5) +
  geom_line(data = data_plot[type == 'model'],
            aes(color = model),
            linetype = 'solid',
            alpha = 0.7) +
  scale_color_manual(values = c('red', 'blue', 'yellow')) +
  facet_grid(participant_id ~ task_version + stim) +
  theme(legend.position = 'top')
```

# Parameter relations

## Pedlr

### alpha0 vs. alpha1

```{r, out.width='100%', fig.height=n_participants}
data_plot = Plot_prepare_consistency(data[model == 'Pedlr']) %>%
  .[variable == 'second_solution']
ggplot(data = data_plot,
       aes(x = value_alpha0,
           y = value_alpha1)) +
  geom_point() +
  facet_grid(participant_id ~ task_version)
```


