---
title: "Summary Stats"
output:
  html_document:
    toc: yes
    self_contained: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    toc_depth: 3
    number_sections: False
    highlight: pygments
    theme: cosmo
    code_folding: "hide"
    df_print: paged
    fig_caption: true
  pdf_document:
    toc: yes
    fig_caption: true
    latex_engine: xelatex
fig.align: "center"
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{AgfaRotisSansSerif}
email: koch@mpib-berlin.mpg.de
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(data.table)
library(here)
library(magrittr)
library(ggplot2)
library(viridis)
library(binhf)
library(pwr)
library(knitr)
library(kableExtra)
library(sdamr)
library(gghalves)
library(lme4)
library(emmeans)
library(papeR)
```

```{r, message=FALSE}
# Get directory of repository
base_path = here::here()

# Load pre-written functions
source_path = file.path(base_path, 'code', 'utils',
                        fsep = .Platform$file.sep)
source_files = list.files(source_path, pattern = "[.][rR]$",
                          full.names = TRUE, recursive = TRUE)
invisible(lapply(source_files, function(x) source(x)))

# Get plot colors/linetypes
custom_guides = Get_plot_guides()
```

```{r}
# Load data
data = Load_data() %>%
  Apply_exclusion_criteria(.) %>%
  Add_comp(.) %>%
  .[, run := as.factor(run)]

# get number of participants (to adjust figure height)
n_participants = length(unique(data$participant_id))
```

---

# Overall performance

```{r, fig.height=0.75*n_participants, out.width='100%'}
# Percentage of optimal choices
check_noc = data %>%
  .[, trial := seq(.N),
    by = c('participant_id', 'run')] %>%
  .[trial_type == 'choice',] %>%
  .[, correct_choice := if(option_left > option_right) 'left' else 'right',
    by = c('participant_id', 'run', 'trial')] %>%
  .[, correct := correct_choice == choice] %>%
  # Get percentage of correct choices (exclude timeouts from overall trials)
  .[, .(perc_correct = sum(as.numeric(correct), na.rm = TRUE) / length(which(!is.na(as.numeric(correct))))),
    by = c('participant_id', 'group', 'run', 'comp')]
```

## Plot

```{r}
data_plot = Prepare_data_for_plot(check_noc)
p_noc_diff_comp_line = ggplot(data = data_plot,
                              aes(x = comp,
                                  y = perc_correct,
                                  color = group,
                                  fill = group)) +
  geom_point(size = 0.2,
             position = position_jitterdodge(dodge.width = 0.3,
                                             jitter.width = 0.2,
                                             jitter.height = 0)) +
  geom_boxplot(width = 0.15,
               color = 'black',
               outlier.shape = NA,
               position = position_dodge(width = 0.3),
               show.legend = FALSE) +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               position = position_dodge(width = 0.3)) +
  scale_color_manual(values = custom_guides) +
  scale_fill_manual(values = custom_guides) +
  facet_grid( ~ run) +
  theme(strip.text.y = element_text(angle = 0),
        legend.position = 'none')
Neurocodify_plot(p_noc_diff_comp_line)
```

## Stats

```{r}
# Assure data types
check_noc$participant_id = as.factor(check_noc$participant_id)
check_noc$group = as.factor(check_noc$group)
check_noc$run = as.factor(check_noc$run)
check_noc$comp = as.factor(check_noc$comp)
check_noc$perc_correct = as.numeric(check_noc$perc_correct)

# LME
lme_noc = lme4::lmer(data = check_noc,
                     perc_correct ~ group * run * comp + (1 | participant_id))
papeR::prettify(Anova(lme_noc))
```

### Main effect run

```{r}
emmeans::emmeans(lme_noc,
                 pairwise ~ run)
```

### Main effect comp

```{r}
emmeans::emmeans(lme_noc,
                 pairwise ~ comp)
```

---

# Critical Comparisons

## Correctness

```{r}
# Within-subject comparison of correctness in critical comparisons
check_noc_diff = check_noc %>%
  data.table::dcast(participant_id + group + run ~ paste0('perc_correct_', comp), value.var = 'perc_correct') %>%
  .[, perc_correct_1v2m2v3 := perc_correct_1v2 - perc_correct_2v3]
```

### Plot

```{r}
data_plot = Prepare_data_for_plot(check_noc_diff)
p_noc_diff_comp_diff = ggplot(data = data_plot,
                              aes(x = run,
                                  y = perc_correct_1v2m2v3,
                                  color = group,
                                  fill = group)) +
  geom_hline(yintercept = 0,
             size = 0.5,
             linetype = 'solid') +
  geom_point(size = 0.5,
              position = position_jitterdodge(dodge.width = 0.2,
                                              jitter.width = 0.08,
                                              jitter.height = 0)) +
  geom_boxplot(width = 0.1,
               color = 'black',
               outlier.shape = NA,
               position = position_dodge(width = 0.2)) +
 stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
              position = position_dodge(width = 0.2)) +
  gghalves::geom_half_violin(side = 1,
                             color = 'transparent',
                             width = 0.3,
                             alpha = 0.5,
                             position = position_nudge(x = 0.15),
                             show.legend = FALSE) +
  scale_y_continuous(limits = c(-max(abs(data_plot$perc_correct_1v2m2v3)),
                                max(abs(data_plot$perc_correct_1v2m2v3)))) +
  scale_fill_manual(values = custom_guides) +
  scale_color_manual(values = custom_guides) +
  labs(title = 'Difference between crit comparisons (1v2 - 2v3)')
Neurocodify_plot(p_noc_diff_comp_diff)
```

### Stats

```{r}
# Assure data types
check_noc_diff$participant_id = as.factor(check_noc_diff$participant_id)
check_noc_diff$group = as.factor(check_noc_diff$group)
check_noc_diff$run = as.factor(check_noc_diff$run)
check_noc_diff$perc_correct_1v2m2v3 = as.numeric(check_noc_diff$perc_correct_1v2m2v3)

# LME
lme_noc_diff = lme4::lmer(data = check_noc_diff,
                     perc_correct_1v2m2v3 ~ group * run + (1 | participant_id))
papeR::prettify(Anova(lme_noc_diff))
```


## RT

```{r}
# Get RT (restricted to critical comparisons 1v2 & 2v3)
check_rt_crit = data %>%
  .[, trial := seq(.N),
    by = c('participant_id', 'run')] %>%
  .[timeout == FALSE, ] %>%
  .[, log_rt := log(rt)] %>%
  data.table::melt(.,
                   id.vars = c('participant_id',
                               'group',
                               'run',
                               'trial',
                               'trial_type',
                               'comp'),
                   measure.vars = c('log_rt')) %>%
  .[trial_type == 'choice' & comp %in% c('1v2', '2v3')]

# Get mean log(RT) of critical comparisons
check_rt_mean_crit = check_rt_crit %>%
  .[, .(mean_log_rt = mean(value)),
    by = c('participant_id',
           'group',
           'run',
           'comp')]

# Get difference 1v2 - 2v3 (within-subject comparison of which )
check_rt_mean_crit_diff = check_rt_mean_crit %>%
  data.table::dcast(participant_id + group + run ~ paste0('mean_log_rt_', comp),
                    value.var = c('mean_log_rt')) %>%
  .[, mean_log_rt_1v2m2v3 := mean_log_rt_1v2 - mean_log_rt_2v3]
```

### Plot

```{r}
data_plot = Prepare_data_for_plot(check_rt_mean_crit_diff)
p_rt_mean_crit_diff = ggplot(data = data_plot,
                             aes(x = run,
                                 y = mean_log_rt_1v2m2v3,
                                 color = group,
                                 fill = group)) +
  geom_hline(yintercept = 0,
             size = 0.5,
             linetype = 'solid') +
  geom_point(size = 0.5,
             position = position_jitterdodge(jitter.width = 0.08,
                                             jitter.height = 0,
                                             dodge.width = 0.3)) +
  geom_boxplot(width = 0.15,
               color = 'black',
               outlier.shape = NA,
               show.legend = FALSE,
               position = position_dodge(width = 0.3)) +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               inherit.aes = TRUE,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               position = position_dodge(width = 0.3),
               show.legend = FALSE) +
  gghalves::geom_half_violin(side = 1,
                             color = NA,
                             width = 0.5,
                             alpha = 0.5,
                             position = position_nudge(x = 0.2),
                             show.legend = FALSE) +
  scale_y_continuous(limits = c(-max(abs(data_plot$mean_log_rt_1v2m2v3)),
                                max(abs(data_plot$mean_log_rt_1v2m2v3)))) +
  scale_color_manual(values = custom_guides) +
  scale_fill_manual(values = custom_guides) +
  labs(title = 'Difference Mean (1v2 - 2v3)')
Neurocodify_plot(p_rt_mean_crit_diff)
```

### Stats

```{r}
# Assure data types
check_rt_mean_crit_diff$participant_id = as.factor(check_rt_mean_crit_diff$participant_id)
check_rt_mean_crit_diff$group = as.factor(check_rt_mean_crit_diff$group)
check_rt_mean_crit_diff$run = as.factor(check_rt_mean_crit_diff$run)
check_rt_mean_crit_diff$comp = as.factor(check_rt_mean_crit_diff$comp)
check_rt_mean_crit_diff$mean_log_rt_1v2m2v3 = as.numeric(check_rt_mean_crit_diff$mean_log_rt_1v2m2v3)

# LME
lme_rt = lme4::lmer(data = check_rt_mean_crit_diff,
                     mean_log_rt_1v2m2v3 ~ group * run + (1 | participant_id))
papeR::prettify(Anova(lme_rt))
```

### Main effect: Group

```{r}
emmeans::emmeans(lme_rt,
                 pairwise ~ group)
```

---

# Estimation

```{r}
# State melt columns (to align data types to avoid warnings)
measure_cols = c('est_1_reward',
                 'est_1_range',
                 'avg_1_running',
                 'est_2_reward',
                 'est_2_range',
                 'avg_2_running',
                 'est_3_reward',
                 'est_3_range',
                 'avg_3_running')

# Get estimation data
check_est = data %>%
  # Get running average of chosen rewards
  .[, ':='(avg_1_running = Get_running_avg(choice_option = option_choice,
                                     choice_outcome = outcome,
                                     stim = 1),
           avg_2_running = Get_running_avg(choice_option = option_choice,
                                     choice_outcome = outcome,
                                     stim = 2),
           avg_3_running = Get_running_avg(choice_option = option_choice,
                                     choice_outcome = outcome,
                                     stim = 3)),
    by = c('participant_id', 'run')] %>%
  .[, forced_rare := as.numeric(as.logical(is_rare) & trial_type == 'forced' & (comp == '1v2' | comp == '2v3'))] %>%
  .[!is.na(est_1_reward),] %>%
  .[, est_trial := seq(.N), by = c('participant_id', 'run')] %>%
  # Unify data types of measure columns
  .[, (measure_cols) := lapply(.SD, as.double), .SDcols = measure_cols] %>%
  data.table::melt(.,
                   id.vars = c('participant_id',
                               'group',
                               'run',
                               'est_trial',
                               'forced_rare'),
                   measure.vars = measure_cols) %>%
  .[, est_stim := substr(variable, 5, 5)] %>%
  .[, type := substr(variable, 7, 9)] %>%
  .[type == 'rew', type := 'reward'] %>%
  .[type == 'ran', type := 'range'] %>%
  .[type == 'run', type := 'r_avg'] %>%
  data.table::dcast(., participant_id + group + run + est_trial + forced_rare + est_stim ~ type,
                    value.var = 'value')

# Merge true means with estimation
check_est_diff = check_est %>%
  # Get difference between estimation and true mean
  .[, diff_from_true := reward - r_avg]

# Get mean estimation accuracy across estimation trials
check_mean_est_diff = check_est_diff %>%
  .[, half := rep(x = c(1,2), each = (max(est_trial)/2)),
    by = c('participant_id', 'group', 'run', 'est_stim')] %>%
  .[, .(mean_diff_from_true = mean(diff_from_true, na.rm = TRUE)),
    by = c('participant_id', 'group', 'run', 'half', 'est_stim')]
```

## Plot

```{r}
data_plot = Prepare_data_for_plot(check_mean_est_diff)

data_plot$half = as.factor(data_plot$half)
levels(data_plot$half) = c('First Half', 'Second Half')
data_plot$run = as.factor(data_plot$run)
levels(data_plot$run) = c('Run 1', 'Run 2')

p_check_mean_est_diff = ggplot(data = data_plot[half == 'Second Half'],
                               aes(x = est_stim,
                                   y = mean_diff_from_true,
                                   fill = group,
                                   color = group)) +
  geom_hline(yintercept = 0,
             size = 0.5) +
  geom_point(position = position_jitterdodge(dodge.width = 0.6,
                                             jitter.width = 0.2,
                                             jitter.height = 0)) +
  geom_boxplot(width = 0.5,
               color = 'black',
               outlier.shape = NA,
               position = position_dodge(width = 0.6)) +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               inherit.aes = TRUE,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               position = position_dodge(width = 0.6),
               show.legend = FALSE)+
  scale_fill_manual(values = custom_guides) +
  scale_color_manual(values = custom_guides) +
  facet_grid(run ~ half)
Neurocodify_plot(p_check_mean_est_diff)
```


## Stats

```{r}
# Assure data types
check_mean_est_diff$participant_id = as.factor(check_mean_est_diff$participant_id)
check_mean_est_diff$group = as.factor(check_mean_est_diff$group)
check_mean_est_diff$run = as.factor(check_mean_est_diff$run)
check_mean_est_diff$est_stim = factor(check_mean_est_diff$est_stim)
levels(check_mean_est_diff$est_stim) = c('Low', 'Mid', 'High')
check_mean_est_diff$mean_diff_from_true = as.numeric(check_mean_est_diff$mean_diff_from_true)

#Only take second half (to allow learning)
check_mean_est_diff_half = check_mean_est_diff %>%
  .[half == '2',]

# LME
lme_est_diff = lme4::lmer(data = check_mean_est_diff_half,
                          mean_diff_from_true ~ group * run * est_stim + (1 | participant_id))
papeR::prettify(Anova(lme_est_diff))
```

### Main effect: Stimulus

```{r}
emmeans::emmeans(lme_est_diff,
                 pairwise ~ est_stim)
```

```{r}
data_plot = Prepare_data_for_plot(check_mean_est_diff_half)

p_check_mean_est_diff = ggplot(data = data_plot[half == 2],
                               aes(x = est_stim,
                                   y = mean_diff_from_true,
                                   fill = est_stim,
                                   color = est_stim)) +
  geom_hline(yintercept = 0,
             size = 0.5) +
  geom_point(position = position_jitterdodge(dodge.width = 0.6,
                                             jitter.width = 0.2,
                                             jitter.height = 0)) +
  geom_boxplot(width = 0.5,
               color = 'black',
               outlier.shape = NA,
               position = position_dodge(width = 0.6)) +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               inherit.aes = TRUE,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               position = position_dodge(width = 0.6),
               show.legend = FALSE)+
  scale_fill_manual(values = custom_guides) +
  scale_color_manual(values = custom_guides) +
  theme(legend.position = 'None')
Neurocodify_plot(p_check_mean_est_diff)
```


## Interaction effect: Group X Run

```{r}
emmeans::emmeans(lme_est_diff,
                 pairwise ~ run | group)
```

# Distance between Low and Mid in estimates

```{r}
check_diff_mid_dist = check_est_diff %>%
  .[, half := rep(x = c(1,2), each = (max(est_trial)/2)),
    by = c('participant_id', 'group', 'run', 'est_stim')] %>%
  data.table::dcast(participant_id + group + run + half + est_trial + forced_rare ~ est_stim,
                    value.var = c('r_avg', 'reward', 'range')) %>%
  .[, ':='(diff_2m1_ravg = r_avg_2 - r_avg_1,
           diff_2m1_est = reward_2 - reward_1,
           diff_3m2_ravg = r_avg_2 - r_avg_2,
           diff_3m2_est = reward_3 - reward_2),
    by = c('participant_id', 'group', 'run', 'est_trial')] %>%
  # Get difference between real 1v2 distance and estimates 1v2 distance
  .[, ':='(diff_est_m_ravg_2m1 = diff_2m1_est - diff_2m1_ravg, 
           diff_est_m_ravg_3m2 = diff_3m2_est - diff_3m2_ravg)] %>%
  # Average within participant
  .[half == 2,] %>%
  .[,.(mean_diff_est_m_ravg_2m1 = mean(diff_est_m_ravg_2m1, na.rm = TRUE),
       mean_diff_est_m_ravg_3m2 = mean(diff_est_m_ravg_3m2, na.rm = TRUE)),
    by = c('participant_id', 'group', 'run', 'half')]
```

## Plot

```{r}
data_plot = Prepare_data_for_plot(check_diff_mid_dist)

ggplot(data = data_plot,
       aes(x = group,
           y = mean_diff_est_m_ravg,
           color = group,
           fill = group)) +
  geom_hline(yintercept = 0) +
  geom_point(alpha = 0.2) +
  geom_boxplot(outlier.shape = NA,
               color = 'black') +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               inherit.aes = TRUE,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               show.legend = FALSE) +
  scale_color_manual(values = custom_guides) +
  facet_grid(~run)
```


## Stats

```{r}
# Assure data types
check_diff_mid_dist$participant_id = as.factor(check_diff_mid_dist$participant_id)
check_diff_mid_dist$group = as.factor(check_diff_mid_dist$group)
check_diff_mid_dist$run = as.factor(check_diff_mid_dist$run)
check_diff_mid_dist$mean_diff_est_m_ravg_2m1 = as.numeric(check_diff_mid_dist$mean_diff_est_m_ravg_2m1)
check_diff_mid_dist$mean_diff_est_m_ravg_3m2 = as.numeric(check_diff_mid_dist$mean_diff_est_m_ravg_3m2)


# LME
lme_est_diff_1v2 = lme4::lmer(data = check_diff_1v2_dist,
                              mean_diff_est_m_ravg ~ group * run + (1 | participant_id))
papeR::prettify(Anova(lme_est_diff_1v2))
```


```{r}
t.test(x = check_diff_1v2_dist[group == 'older']$mean_diff_est_m_ravg, mu = 0)
t.test(x = check_diff_1v2_dist[group == 'younger']$mean_diff_est_m_ravg, mu = 0)
```


## Plot 

```{r}
data_plot = Prepare_data_for_plot(check_diff_1v2_dist)

ggplot(data = data_plot,
       aes(x = group,
           y = mean_diff_est_m_ravg,
           color = group,
           fill = group)) +
  geom_hline(yintercept = 0) +
  geom_point(alpha = 0.2) +
  geom_boxplot(outlier.shape = NA,
               color = 'black') +
  stat_summary(fun = 'mean',
               geom = 'point',
               na.rm = TRUE,
               shape = 23,
               inherit.aes = TRUE,
               fill = 'white',
               size = 1.5,
               stroke = 0.5,
               show.legend = FALSE) +
  scale_color_manual(values = custom_guides) +
  facet_grid(~run)
```



