---
title: "Summary Stats"
author: "Christoph Koch"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(data.table)
library(here)
library(magrittr)
library(ggplot2)
library(viridis)
```

```{r}
# Get directory of repository
base_path = here::here()

# Load pre-written functions
source_path = file.path(base_path, 'code', 'utils',
                        fsep = .Platform$file.sep)
source_files = list.files(source_path, pattern = "[.][rR]$",
                          full.names = TRUE, recursive = TRUE)
invisible(lapply(source_files, function(x) source(x)))
```

```{r}
# Load data
data = Load_data()
```

# Errors in forced choices

```{r}
# Summary: Mistakes on forced choices
check_fce = data %>%
  .[trial_type == 'forced',] %>%
  .[, forced_error := forced != choice] %>%
  .[, .(n_forced = length(forced),
        n_error = sum(as.numeric(forced_error))), by = 'participant_id'] %>%
  .[, perc_forced_error := round((n_error/n_forced) * 100, 2)] %>%
  .[, count := seq(.N), by = n_error]

# Plot errors for each participant
p_fce = ggplot(data = check_fce,
               aes(x = n_error,
                   y = count,
                   label = participant_id)) +
  geom_label() +
  labs(x = 'Number of errors during forced choices',
       y = 'N') +
  scale_y_continuous(limits = c(1,max(check_fce$count)),
                     breaks = seq(max(check_fce$count, by = 1))) +
  theme()
p_fce
```

# Estimation track

```{r}
check_est = data %>%
  .[!is.na(est_1_reward),] %>%
  .[, est_trial := seq(.N), by = c('participant_id', 'task_version')] %>%
  data.table::melt(.,
                   id.vars = c('participant_id',
                               'task_version',
                               'est_trial'),
                   measure.vars = c('est_1_reward',
                                    'est_1_range',
                                    'est_2_reward',
                                    'est_2_range',
                                    'est_3_reward',
                                    'est_3_range')) %>%
  .[, est_stim := substr(variable, 5, 5)] %>%
  .[, type := substr(variable, 7, 9)] %>%
  .[type == 'rew', type := 'reward'] %>%
  .[type == 'ran', type := 'range'] %>%
  data.table::dcast(., participant_id + task_version + est_trial + est_stim ~ type, value.var = 'value')

# Get true mean of options
rewards = data %>%
  .[, c('participant_id', 'task_version', 'option_left', 'reward_stim_1', 'option_right', 'reward_stim_2')]
rewards_left = rewards[, c('participant_id', 'task_version', 'option_left', 'reward_stim_1')] %>%
  setnames(., c('option_left', 'reward_stim_1'), c('est_stim', 'reward'))
rewards_right = rewards[, c('participant_id', 'task_version', 'option_right', 'reward_stim_2')] %>%
  setnames(., c('option_right', 'reward_stim_2'), c('est_stim', 'reward'))
true_means = rbind(rewards_left, rewards_right) %>%
  .[, .(mean = mean(reward)), by = c('participant_id', 'task_version', 'est_stim')]

p_est = ggplot(data = check_est,
               aes(x = est_trial,
                   y = reward,
                   color = est_stim)) +
  geom_hline(data = true_means,
             aes(yintercept = mean),
             linetype = 'dashed') +
  geom_ribbon(aes(ymin = reward - range,
                  ymax = reward + range),
              alpha = 0.3) +
  geom_point(size = 0.8) +
  geom_path() +
  facet_grid(participant_id ~ task_version + est_stim) +
  scale_color_viridis(option = 'D', discrete = TRUE)
p_est
```

# Check RT

```{r}
check_rt = data %>%
  .[, trial := seq(.N),
    by = c('participant_id', 'task_version')] %>%
  .[, comp := paste(sort(c(option_left, option_right)), collapse = 'v'),
    by = c('participant_id', 'task_version', 'trial')] %>%
  .[timeout == FALSE, ] %>%
  data.table::melt(.,
                   id.vars = c('participant_id', 'task_version', 'trial', 'trial_type', 'comp'),
                   measure.vars = 'rt')
p_rt = ggplot(data = check_rt,
       aes(x = trial_type,
           y = value)) +
  geom_jitter(width = 0.1,
              size = 0.2) +
  facet_grid(participant_id ~ task_version + comp)
p_rt
```



