---
title: "Summary Designs"
output:
  html_document:
    toc: yes
    self_contained: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    toc_depth: 3
    number_sections: False
    highlight: pygments
    theme: cosmo
    code_folding: "hide"
    df_print: paged
    fig_caption: true
  pdf_document:
    toc: yes
    fig_caption: true
    latex_engine: xelatex
fig.align: "center"
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{AgfaRotisSansSerif}
email: koch@mpib-berlin.mpg.de
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(data.table)
library(here)
library(magrittr)
library(ggplot2)
library(viridis)
library(binhf)
library(pwr)
library(knitr)
library(kableExtra)
```

```{r}
# Get directory of repository
base_path = here::here()

# Load pre-written functions
source_path = file.path(base_path, 'code', 'utils',
                        fsep = .Platform$file.sep)
source_files = list.files(source_path, pattern = "[.][rR]$",
                          full.names = TRUE, recursive = TRUE)
invisible(lapply(source_files, function(x) source(x)))
```

```{r}
# Load designs
file_pattern = file.path(base_path, 'pedlr-task', 'client', 'public', 'designs', '*run-1.tsv',
                         fsep = .Platform$file.sep)
files_r1 = Sys.glob(file_pattern)
file_pattern = file.path(base_path, 'pedlr-task', 'client', 'public', 'designs', '*run-2.tsv',
                         fsep = .Platform$file.sep)
files_r2 = Sys.glob(file_pattern)
data = data.table()
for(i in seq(length(files_r1))){
  file_r1 = files_r1[i]
  file_r2 = files_r2[i]
  temp_r1 = data.table::fread(file_r1, sep = '\t', na.strings = 'n/a')
  temp_r1$design_name = substr(basename(file_r1), 0,15)
  temp_r2 = data.table::fread(file_r2, sep = '\t', na.strings = 'n/a')
  temp_r2$design_name = substr(basename(file_r2), 0,15)
  temp = rbind(temp_r1, temp_r2)
  temp$n_design = i
  data = rbind(data, temp)
}
n_designs = max(unique(data$n_design))
```

# Sampling

```{r, fig.height=n_designs, fig.width=6, out.width='100%'}
data_plot = data %>%
  .[, .(stim = c(option_left, option_right),
        outcome = c(reward_stim_1, reward_stim_2)),
    by = c('n_design', 'task_version', 'design_name')] %>%
  .[, stim := as.factor(stim)] %>%
  # Add each value once so all outcomes are counted for each stimulus
  .[, .(outcome = c(outcome, seq(1,100))),
    by = c('n_design', 'task_version', 'design_name', 'stim')] %>%
  # Count occurence of outcomes for each stimulus
  .[, .(count = .N),
    by = c('n_design', 'task_version', 'design_name', 'stim', 'outcome')] %>%
  # Subtract the artificially added outcomes
  .[, count := count - 1]

data_plot_mean = data %>%
  .[, .(stim = c(option_left, option_right),
        outcome = c(reward_stim_1, reward_stim_2)),
    by = c('n_design', 'task_version', 'design_name')] %>%
  .[, stim := as.factor(stim)] %>%
  .[, .(mean_outcome = mean(outcome)),
    by = c('n_design', 'task_version', 'design_name', 'stim')]

data_plot_diff = data_plot_mean %>%
  data.table::dcast(., n_design + task_version + design_name ~ paste0('mean_', stim), value.var = 'mean_outcome') %>%
  .[, ':='(diff2m1 = mean_2 - mean_1,
           diff3m2 = mean_3 - mean_2)] %>%
  .[, ':='(loc2m1 = mean_1 + (diff2m1/2),
           loc3m2 = mean_2 + (diff3m2/2))]
           

ggplot(data = data_plot,
       aes(x = outcome,
           y = count,
           color = stim,
           fill = stim,
           group = stim)) +
  theme_bw() +
  #geom_line() +
  geom_area(data = data_plot[stim == 1],
            alpha = 0.7) +
  geom_area(data = data_plot[stim == 3],
            alpha = 0.7) +
  geom_area(data = data_plot[stim == 2],
            alpha = 0.7,
            color = 'black') +
  geom_label(data = data_plot_mean,
             aes(x = mean_outcome,
                 y = max(data_plot$count) + 3,
                 label = round(mean_outcome,2),
                 color = NA),
             color = 'white',
             size = 2) +
  geom_label(data = data_plot_diff,
             aes(x = loc2m1,
                 y = max(data_plot$count) + 6,
                 color = NA,
                 fill = NA,
                 group = NA,
                 label = round(diff2m1, 2)),
             color = 'white',
             fill = 'black',
             size = 1.5) +
  geom_label(data = data_plot_diff,
             aes(x = loc3m2,
                 y = max(data_plot$count) + 6,
                 color = NA,
                 fill = NA,
                 group = NA,
                 label = round(diff3m2, 2)),
             color = 'white',
             fill = 'black',
             size = 1.5) +
  scale_x_continuous(limits = c(1,100), expand = c(0,0)) +
  scale_y_continuous(limits = c(0,max(data_plot$count) + 8), expand = c(0,0)) +
  facet_grid(n_design ~ task_version) +
  theme(legend.position = 'none',
        panel.grid = element_blank()) +
  guides(alpha = FALSE)
```

## Distance between bandits

```{r}
bla = data_plot_diff %>%
  data.table::melt(.,
                   id.vars = c('n_design', 'task_version', 'design_name')) %>%
  .[variable %in% c('diff2m1', 'diff3m2'), ]
ggplot(bla,
       aes(x = variable,
           y = value)) +
  geom_point() +
  geom_boxplot(outlier.shape = NA)
```


# Vary range

```{r}
data_range = data %>%
  .[, .(stim = c(option_left, option_right),
        outcome = c(reward_stim_1, reward_stim_2)),
    by = c('n_design', 'task_version')] %>%
  .[, stim := as.factor(stim)] %>%
  # Add each value once so all outcomes are counted for each stimulus
  .[, .(outcome = c(outcome, seq(1,100))),
    by = c('n_design', 'task_version', 'stim')] %>%
  # get average outcome for each design and stimulus
  .[, .(bandit_mean = mean(outcome)),
    by = c('n_design', 'task_version', 'stim')] %>%
  # Get vary range across all designs
  .[, .(min = min(bandit_mean),
        max = max(bandit_mean)),
    by = c('stim')] %>%
  # get range
  .[, range := max - min]

knitr::kable(data_range) %>%
  kableExtra::kable_styling()
```


# Estimation trials

```{r, fig.height=n_designs/3, fig.width=6, out.width='100%'}
data_plot = data %>%
  .[, trial := seq(.N),
    by = c('n_design', 'task_version')] %>%
  .[with_rating == 1, ] %>%
  .[, est_trial := seq(.N),
    by = c('n_design', 'task_version')] %>%
  .[, rating_type := is_rare + ((free_choice - 1) * -1),
    by = c('n_design', 'task_version', 'est_trial')] %>%
  .[, rating_type := factor(rating_type)]
levels(data_plot$rating_type) = c('rating',
                                  'rating after possible rare',
                                  'rating after forced rare')
```

## Placement

```{r}
ggplot(data = data_plot,
       aes(x = est_trial,
           y = 0)) +
  # geom_path() +
  # geom_point(aes(color = rating_type)) +
  geom_tile(aes(color = rating_type,
                fill = rating_type)) +
  scale_color_viridis(option = 'D', discrete = TRUE) +
  scale_fill_viridis(option = 'D', discrete = TRUE) +
  facet_grid(n_design ~ task_version) +
  theme(axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = 'top')
```

## Min distance between est trials

```{r}
# First est trials possible after
min(data_plot$trial)

# Min distance between est trials
min(diff(data_plot$trial)[diff(data_plot$trial) > 0])

# Average diastance between estimation trials
mean(diff(data_plot$trial)[diff(data_plot$trial) > 0])
sd(diff(data_plot$trial)[diff(data_plot$trial) > 0])

```


